[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache'
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 200

[profile.default.remappings]
"@openzeppelin/contracts/" = "node_modules/@openzeppelin/contracts/"
"@openzeppelin/contracts-upgradeable/" = "node_modules/@openzeppelin/contracts-upgradeable/"
