[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'cache'
solc_version = '0.8.19'
optimizer = true
optimizer_runs = 200

[profile.default.remappings]
"@openzeppelin/contracts/" = "node_modules/@openzeppelin/contracts/"
"@openzeppelin/contracts-upgradeable/" = "node_modules/@openzeppelin/contracts-upgradeable/"
